---
title: "Final_lab"
author: "Kylian SANTOS"
format: html
editor: visual
---

## Link to github repository

<https://github.com/KylianSts/Science_fiction>

```{r}
#| message: false
here::i_am("Science_fiction.Rproj")
library(here)
library(dplyr)
library(tidyr)
library(stringr)
library(vroom)
library(ggplot2)
library(knitr)

```

# Main dataset import

```{r}
file_content <- readLines("Data/Planet_data.csv")

# Replace all '?' with NA in the entire file content
file_content <- gsub("\\?", "NA", file_content)

writeLines(file_content, "Data/Planet_data.csv")

planet_data <- vroom("Data/Planet_data.csv", delim = ':', locale = locale(decimal_mark = ","))
```

```{r}
nb_row <- planet_data |> nrow()
nb_variable <- planet_data |> ncol()

if (nb_row == 971 && nb_variable == 8) {
  cat('There are no missing planets and variables.\n')
} else {
  cat('Data not correctly loaded.\n')
}
```
```{r}
planet_data |> select(where(is.numeric))
```

```{r}
#| message: false
summary_table <- planet_data %>%
  summarise(
    nb_ob = n(),
    nb_var = ncol(.)
    )

kable(summary_table)
```
```{r}
ggplot(planet_data, aes(x = `Radius (Earth)`, y = Density)) +
  geom_point(na.rm = TRUE) +
  labs(title = "Density of Planets as a Function of Radius",
       x = "Radius (Earth)",
       y = "Density")
```

# Improved data representation

```{r}
terrain_df <- planet_data %>%
  reframe(
    terrain_type = str_split(`terrain type`, ",") %>% unlist(),
    Planet_code = rep(Planet_code, lengths(str_split(`terrain type`, ",")))
  ) %>%
  select(Planet_code, terrain_type)

climate_df <- planet_data %>%
  reframe(
    climate_type = str_split(Type_climate, ",") %>% unlist(),
    Planet_code = rep(Planet_code, lengths(str_split(Type_climate, ",")))
  ) %>%
  select(Planet_code, climate_type)
```

```{r}
ggplot(climate_df, aes(x = Planet_code, fill = climate_type)) +
  geom_bar(position = "stack")
```
```{r}
ggplot(na.omit(terrain_df), aes(x = Planet_code, fill = terrain_type)) +
  geom_bar(position = "stack") 
```
# Star data

```{r}
star_data <- vroom("Data/STARS.csv", delim = ':')
```

```{r}
nb_star_row <- nrow(star_data)
nb_star_variable <- ncol(star_data)

if (nb_star_row == 540 && nb_star_variable == 8) {
  cat('Star data loaded successfully.\n')
} else {
  cat('Star data not correctly loaded.\n')
}
```



